### PR TITLE
Created Footer

### PR DESCRIPTION
**Pull request by AadiXC0DE**

### CODE REVIEW

**Comment by AadiXC0DE** [comment]
Fixes #3

**Comment by viralRupani** [comment]
Thank you for contributing 😄. but why do you have one commit which is saying created navbar? I know it was a little mistake but no problem I got it. and also please make sure next time you are contributing to any project please see what conventions they are using. as in my project you have used different class name styles.

**Comment by AadiXC0DE** [comment]
I will remove the Navbar Commit, Here is the footer screenshot
image

**Comment by viralRupani** [comment]
> I will remove the Navbar Commit, Here is the footer screenshot image

oh, np I have merged your pr, did you make this footer using ai?

**Comment by AadiXC0DE** [comment]
No, but I used AI in generating the 'Subscribe the newsletter' animation and in adding some comments to increase code readability.

**Comment by viralRupani** [comment]
oh my gosh, I had to revert you have used class instead of className.

**Pull request merged**
